name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.12"

    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/src" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install core dependencies and test tools
          python -m pip install numpy scipy matplotlib pandas h5py pytest
          # Install the project package
          python -m pip install .

      - name: Run unit tests
        run: pytest --maxfail=1 --disable-warnings -q

      - name: Run CLI demo
        run: python scripts/lattice_sweep_demo.py
