name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'pyproject.toml'
      - 'pytest.ini'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - '.github/workflows/**'
      - 'pyproject.toml'
      - 'pytest.ini'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.12"

    steps:
      - uses: actions/checkout@v3
        with:
          path: negative-energy-generator
          
      - uses: actions/checkout@v3
        with:
          repository: arcticoder/lqg-first-principles-gravitational-constant
          path: lqg-first-principles-gravitational-constant

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=${{ github.workspace }}/negative-energy-generator/src" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Install the local gravitational constant package first
          python -m pip install ./lqg-first-principles-gravitational-constant
          # Install core dependencies and test tools
          python -m pip install numpy scipy matplotlib pandas h5py pytest
          # Install the project package
          cd negative-energy-generator
          python -m pip install .

      - name: Run unit tests
        run: |
          cd negative-energy-generator
          pytest --maxfail=1 

      - name: Run CLI demo
        run: |
          cd negative-energy-generator
          python scripts/lattice_sweep_demo.py
          
      - name: Run backreaction demo
        run: |
          cd negative-energy-generator
          python scripts/backreaction_demo.py
      - name: Run dynamic evolution demo
        run: |
          cd negative-energy-generator
          python scripts/dynamic_evolution_demo.py
      - name: Run dynamic evolution analysis
        run: |
          cd negative-energy-generator
          python scripts/dynamic_evolution_analysis.py
      - name: Run dynamic evolution report
        run: |
          cd negative-energy-generator
          python scripts/dynamic_evolution_report.py